config/routes.rb
Rails.application.routes.draw do
resources :tsubuyakis
root 'tsubuyakis#index'
devise_for :users
resources :users do
    member do
      get :following, :followers
    end
end
resources :relationships,       only: [:create, :destroy]

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tsubuyaki.rb
class Tsubuyaki < ActiveRecord::Base
  belongs_to :user
  validates :tweet, presence: :true, length: { maximum: 140 }
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tsubuyakis, dependent: :destroy
  mount_uploader :image, ImageUploader

  has_many :active_relationships, class_name:  "Relationship",foreign_key: "follower_id",dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

   # ユーザーのステータスフィードを返す
  def feed
    Tsubuyaki.where("user_id IN (:following_ids) OR user_id = :user_id",
                    following_ids: following_ids, user_id: id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:description])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image_url])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:description])
    devise_parameter_sanitizer.permit(:account_update, keys: [:image_url])
    devise_parameter_sanitizer.permit(:account_update, keys: [:image])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    redirect_to @user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end

private
  def relationship_params
    params.require(:relationship).permit(:follower_id, :followed_id)
  end
  def logged_in_user
      unless signed_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end


end

app/controllers/tsubuyakis_controller.rb
class TsubuyakisController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_tsubuyaki, only: :detroy
  before_action :correct_user,   only: :destroy
  def index
    @tweets = Tsubuyaki.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @tweet = Tsubuyaki.new
  end

  def create
    @tweet = Tsubuyaki.new(tsubuyaki_params)
    @tweet.user_id =current_user.id
    if @tweet.save
      redirect_to tsubuyakis_path, notice: 'ツイートできました！'
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    @tweet = Tsubuyaki.find(params[:id])
    @tweet.destroy
    flash[:success] = "your tweet  deleted"
    redirect_to request.referrer || root_url
  end

  private
    def set_tsubuyaki
      @tweet = Tsubuyaki.find(params[:id])
    end

    def tsubuyaki_params
      params.require(:tsubuyaki).permit(:tweet,:user_id)
    end

    def correct_user
      @tweet = current_user.tsubuyakis.find_by(id: params[:id])
      redirect_to root_url if @tweet.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follower'
  end



  def show
    @user = User.find(params[:id])
  end



  private
  def user_params
    params.require(:user).permit(:name, :email,:password, :password_confirmation, :image, :remember_digest)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tsubuyakis_helper.rb
module TsubuyakisHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default bootsnav">
    <div class="container">
        <!-- Start Header Navigation -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                <i class="fa fa-bars"></i>
            </button>
        </div>
        <!-- End Header Navigation -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-menu">

           <ul class="nav navbar-nav navbar-left">

                <li><%= link_to "ホーム", tsubuyakis_path %></li>
                <li><%= link_to "新しくつぶやく", new_tsubuyaki_path %></li>
                <% if user_signed_in? %>
                  <li><%= link_to '設定変更', edit_user_registration_path %></li>
                  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？'} %></li>
                <% else %>
                  <li><%= link_to '新規ユーザー登録', new_user_registration_path %></li>
                  <li><%= link_to 'ログイン', new_user_session_path %></li>
                <% end %>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ツイッター的な何か</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <%= yield %>

</div>


</body>
</html>

app/views/tsubuyakis/edit.html.erb
<h1>Tsubuyakis#edit</h1>
<p>Find me in app/views/tsubuyakis/edit.html.erb</p>

app/views/tsubuyakis/index.html.erb
<%= image_tag 'spartter.png' ,alt:'spartter' %>
<div class="row">

  <div class='col-md-3' >
    <div class="top-profile">
      <div class="thumbnail">
        <% if user_signed_in? %>
          <% user = current_user %>
          <%= link_to image_tag(user.image,{alt:'プロフ画像'}), user_path(user) %>
          <div class="caption">
            <p>ユーザー名:<%= user.name %></p>
            <p>ユーザー詳細:<%= user.description %></p>
          </div>
          <section class="stats">
          <%= render 'users/stats' %>
          </section>
        <% end %>
      </div>
    </div>
  </div>
  <div class = 'col-md-9'>
        <h3>全てのつぶやき</h3>
        <hr class="style6">
        <% @tweets.each do |tweet| %>
          <div class="article">
                <p>つぶやいた人：<%= link_to tweet.user.name,tweet.user %></p>
                <p><i>つぶやき日時：<%= tweet.created_at %></i></p>
                <p><strong>つぶやき：<%= simple_format(tweet.tweet) %></strong></p>
                <% if current_user==(tweet.user)  %>
                    <%= link_to "削除", tweet, method: :delete,data: {confirm: "本当に削除しますか?"} ,class: "btn btn-warning"%>
                <% end %>
                <hr class= "style6">
          </div>
        <% end %>
        <%= paginate @tweets %>
  </div>
</div>

app/views/tsubuyakis/new.html.erb
<h1>新規投稿</h1>
<% if @tweet.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <div id="error_explanation">
          <h4><%= @tweet.errors.count %>件のエラーがあります。</h4>
          <ul>
          <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>
<%= form_for @tweet do |f| %>
      <div class="form-group">
        <%= f.label 'ツイート内容' %>
        <%= f.text_field :tweet, autocomplete: "off",class: "form-control" %>
      </div>
      <%= f.submit 'ツイートする', class: "btn btn-primary" %>
<% end %>

app/views/tsubuyakis/show.html.erb
<h1>Tsubuyakis#show</h1>
<p>Find me in app/views/tsubuyakis/show.html.erb</p>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user==(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>


      <%=f.label :image,"ユーザー画像" %>

      <%= f.file_field :image %>

      <%= f.label :name, "ユーザー名" %>
      <%= f.text_field :name, class: 'form-control'  %>
      <%= f.label :profile, "プロフィール" %>
      <%= f.text_field :profile, class: 'form-control'  %>
      <%= f.label :email, "メールアドレス" %>
      <%= f.text_field :email, class: 'form-control'  %>
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation,"パスワードの確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "作成",  class: "btn btn-primary" %>
      <% unless @user.new_record? %>
        <p>パスワードを変更しないときはパスワード入力欄を空にしてください。</p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-lg" %>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= link_to image_tag(@user.image,{alt:'プロフ画像'}), edit_user_registration_path %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'users/stats' %>
      </section>

  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if signed_in? %><br>
    <% @tsubuyakis = @user.tsubuyakis.order(created_at: :desc) %>
    <% @tsubuyakis.each do |tweet|  %>
      <p><%= tweet.tweet  %></p>
      <p><%= tweet.created_at %></p>
      <hr class="style6">
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% @user.following.each do |user| %>
<table>
<tr>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
<table>
<tr>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>